# These are supported funding model platforms

open_collective: https://opencollective.com/system-design
custom: ['https://www.buymeacoffee.com/karanps', 'https://www.paypal.com/paypalme/karanpratapsingh']
